version: "3.7"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    volumes:
      - ${USERDIR}/volumes/jackett:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${USERDIR}/volumes/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.backend=jackett
      - traefik.frontend.rule=Host:jackett.${DOMAINNAME}
      - traefik.port=9117
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy

