version: "3.7"
services:
  plex:
    container_name: plex
    restart: always
    image: linuxserver/plex
    volumes:
      - ${USERDIR}/volumes/plex/config:/config
      - ${USERDIR}/volumes/plex/transcode_tmp:/transcode
      - ${USERDIR}/volumes/shared:/shared
      - ${TV_SERIES_DIR}:/data/tvshows
      - ${MOVIES_DIR}:/data/movies
    environment:
      - VERSION=latest
      - TZ=${TIMEZONE}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
    network_mode: host
    labels:
      - traefik.enable=true
      - traefik.backend=plex
      - traefik.frontend.rule=Host:plex.${DOMAINNAME}
      - traefik.port=32400
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
