version: "3.7"
services:
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    restart: always
    volumes:
      - ${USERDIR}/configuration/ddclient/ddclient.conf:/config/ddclient.conf:ro
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TIMEZONE}
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
