version: "3.7"
services:
  ddclient:
    image: digrouz/ddclient
    container_name: ddclient
    restart: always
    volumes:
      - ${USERDIR}/volumes/ddclient/ddclient.conf:/etc/ddclient/ddclient.conf
    environment:
    - DOCKUID=${PUID}
    - DOCKGID=${PGID}
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
