version: "3.7"
services:
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    restart: always
    volumes:
      - ${USERDIR}/volumes/ddclient:/config
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
