version: "3.7"
services:
  openvpn-sa:
    image: linuxserver/openvpn-as
    container_name: openvpn-sa
    restart: always
    volumes:
      - ${USERDIR}/volumes/openvpn-sa:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    environment:
      - TZ=${TIMEZONE}
      - PGID=${PGID}
      - PUID=${PUID}
      - INTERFACE=${VPN_INTERFACE}
    cap_add:
      - NET_ADMIN
