version: "3.7"
services:
  webserver:
    image: php:7.2.12-apache
    container_name: webserver
    restart: always
    volumes:
      - ${USERDIR}/volumes/webserver:/var/www/html
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.backend=webserver
      - traefik.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}
      - traefik.port=80
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy

