version: "3.7"
services:
  nextcloud:
    container_name: nextcloud
    restart: always
    image: linuxserver/nextcloud
    volumes:
      - ${USERDIR}/volumes/nextcloud:/config
      - ${DOWNLOADS_DIR}:/data
      - ${USERDIR}/volumes/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.backend=nextcloud
      - traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}
      - traefik.port=443
      - traefik.protocol=https
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
networks:
  traefik_proxy:
    name: traefik_proxy
