version: "3.7"
services:
  minecraft:
    image: linuxserver/mcmyadmin2
    container_name: minecraft
    restart: always
    volumes:
      - ${USERDIR}/volumes/minecraft:/minecraft
    ports:
      - "25565:25565"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - traefik.enable=true
      - traefik.backend=minecraft
      - traefik.frontend.rule=Host:minecraft.${DOMAINNAME}
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=example.com
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
