version: "3.7"
services:
  organizr:
    image: lsiocommunity/organizr
    container_name: organizr
    restart: always
    volumes:
      - ${USERDIR}/volumes/organizr:/config
      - ${USERDIR}/volumes/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.backend=organizr
      - traefik.frontend.rule=Host:organizr.${DOMAINNAME}
      - traefik.port=80
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
