version: "3.7"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - ${USERDIR}/volumes/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
      - ${USERDIR}/volumes/shared:/shared
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.backend=radarr
      - traefik.frontend.rule=Host:radarr.${DOMAINNAME}
      - traefik.port=7878
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
