version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${USERDIR}/volumes/sonarr:/config
      - ${DOWNLOADS_DIR}/complete:/downloads
      - ${TV_SERIES_DIR}:/tv
      - ${USERDIR}/volumes/shared:/shared
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.backend=sonarr
      - traefik.frontend.rule=Host:sonarr.${DOMAINNAME}
      - traefik.port=8989
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=example.com
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    name: traefik_proxy
