[backends]
  [backends.backend-webmin]
    [backends.backend-webmin.servers]
      [backends.backend-webmin.servers.server-webmin-ext]
        url = "http://127.0.0.1:10000"
        weight = 0

[frontends]
  [frontends.frontend-webmin]
    backend = "backend-webmin"
    passHostHeader = true
    [frontends.frontend-webmin.routes]
          [frontends.frontend-webmin.routes.route-pihole-ext]
        rule = "Host:webmin.devoralive.com"
